# Permalinks
permalink:           pretty

# Setup
title:               koscew
tagline:             The Road to Programming at Mid-30s
url:                 http://koscew.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              koscew
  url:               
  email:             

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/koscew

# Gems
gems:
  - 
  - 

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
